import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'João Knisspell - Portfólio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-gradient-to-br from-fuchsia-100 via-slate-100 to-slate-200 antialiased dark:bg-gradient-to-l dark:from-zinc-900 dark:via-zinc-900 dark:to-zinc-900">
          {children}
        </main>
      </body>
    </html>
  )
}
